[package]
name = "phoenix"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
serial_test = "3.1.1"

[dependencies]
glfw-sys = { path = "../glfw-sys" }
thiserror = "1.0.61"
gl = "0.14.0"
image = "0.25.1"
cgmath = "0.18.0"